name: booking_app
description: Bootcamp Flutter Booking App
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  logging: ^1.2.0
  flutter_screenutil: ^5.9.0
  auto_route: ^5.0.2
  get_it: ^7.6.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: any
  build_runner: ^2.1.8


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Citta-Standing.png
    - assets/images/Citta-Standing-1.png
    - assets/images/Citta-Standing-2.png
    - assets/images/Citta-Avatar.png
    - assets/images/Citta-Avatar-1.png
    - assets/images/Citta-Avatar-2.png
    - assets/images/Citta-Coffee-Shop.png
    - assets/images/Citta-Coffee-Shop-1.png
    - assets/images/Citta-Coffee-Shop-2.png
    - assets/images/Citta-Giant-Phone.png
    - assets/images/Citta-Giant-Phone-1.png
    - assets/images/Citta-House.png
    - assets/images/Citta-Living-Room.png
    - assets/images/Citta-Living-Room-1.png
    - assets/images/Citta-Party-Time.png
    - assets/images/Citta-Party-Time-1.png
    - assets/images/Citta-Plants.png
    - assets/images/Citta-Plants-1.png
    - assets/images/Citta-Plants-2.png
    - assets/images/Citta-Plants-3.png
    - assets/images/Citta-Plants-4.png
    - assets/images/Citta-Plants-5.png
    - assets/images/Citta-Avatar-and-Backdrop.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf